# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #
from __future__ import annotations

from enum import Enum
from typing import Any, Sequence, Union, overload

_IdxElType = Union[int, slice]
IndexType = Union[Sequence[_IdxElType], _IdxElType]
ShapeType = Sequence[int]

class DType(Enum): ...

class Device:
    def __str__(self) -> str: ...
    @property
    def stats(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def is_host(self) -> bool: ...

class Tensor:
    shape: ShapeType
    rank: int
    is_contiguous: bool
    is_host: bool
    num_elements: int

    @overload
    def __init__(
        self,
        shape: ShapeType,
        dtype: DType,
        device: Device,
    ) -> None: ...
    @overload
    def __init__(self, shape: numpy.ndarray, device: Device) -> None: ...
    def view(self, shape: ShapeType, dtype: DType) -> Tensor: ...
    def set(self, index: IndexType, value: Any) -> None: ...
    def get(self, index: IndexType) -> Tensor: ...
    def item(self) -> Any: ...
    def copy_to(self, device: Device) -> Tensor: ...
    def zeros(self) -> None: ...
    @staticmethod
    def from_dlpack(arg0: Any) -> Tensor: ...
    @property
    def device(self) -> Device: ...
    @property
    def dtype(self) -> Dtype: ...
    def __dlpack__(
        self, *, stream: Any = None, _mmap: Any = None
    ) -> capsule: ...
    def __dlpack_device__(self) -> tuple: ...

def cpu_device(device_id: int) -> Device: ...
def accelerator(device_id: int) -> Device: ...
def accelerator_count() -> int: ...

__version__: str = ...
