# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #
from enum import Enum

class DType(Enum):
    float_8e4m3 = ...
    float_8e4m3fn = ...
    float_8e4m3fnuz = ...
    float_8e5m2 = ...
    float_8e5m2fnuz = ...
    bfloat16 = ...
    bool = ...
    float16 = ...
    float32 = ...
    float64 = ...
    int16 = ...
    int32 = ...
    int64 = ...
    int8 = ...
    uint16 = ...
    uint32 = ...
    uint64 = ...
    uint8 = ...
    unknown = ...

    @property
    def size_in_bytes(self) -> int: ...
