# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #
from enum import Enum

class DType(Enum):
    bfloat16 = ...
    bool = ...
    float16 = ...
    float32 = ...
    float64 = ...
    int16 = ...
    int32 = ...
    int64 = ...
    int8 = ...
    uint16 = ...
    uint32 = ...
    uint64 = ...
    uint8 = ...
    unknown = ...

    @property
    def size_in_bytes(self) -> int: ...
